apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rice-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://bitbucket.org/agroproag/rice-infra.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: rice

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
